---
name: Release Candidate

on:
  workflow_dispatch:
    inputs:
      version:
        description: Release candidate version (format `X.X.X`, e.g. `2.0.1`).
        required: true
      date:
        description: Release candidate date stamp (format `YYYYMMDD`, e.g. `20240430`).
        required: true

env:
  RC_BRANCH_NAME: ${{ github.event.inputs.version }}-${{ github.event.inputs.date }}

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-22.04
    steps:
      - name: Check docs build
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: husarion
          repo: docs_new
          github_token: ${{ secrets.RAFAL_ACCESS_TOKEN }}
          workflow_file_name: test-parser.yaml
          ref: master
          client_payload: '{"husarion_ugv_branch": "ros2-devel"}'

  # TODO: Add unit testing when ready
  unit_tests:
    name: Unit tests
    runs-on: ubuntu-22.04
    steps:
      - name: Run unit tests
        run: echo "Unit tests are not fully implemented yet -> SKIPPING!"

  docker:
    name: Docker
    needs: unit_tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update docker image tag
        run: |
          sed -i 's/\(husarion\/panther:humble-\)[^[:space:]]*/\1${{ env.RC_BRANCH_NAME }}/g' docker/demo/compose.hardware.yaml
          sed -i 's/\(husarion\/panther:humble-\)[^[:space:]]*/\1${{ env.RC_BRANCH_NAME }}/g' docker/demo/compose.rviz.yaml
          sed -i 's/\(husarion\/panther-gazebo:humble-\)[^[:space:]]*/\1${{ env.RC_BRANCH_NAME }}/g' docker/demo/compose.simulation.yaml

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Update tags in compose files
          author_name: action-bot
          author_email: action-bot@action-bot.com
          new_branch: ${{ env.RC_BRANCH_NAME }}

      - name: Build Docker
        uses: ./.github/workflows/build-docker.yaml
        with:
          build_type: development

  os_image:
    name: OS image
    needs: docker
    runs-on: ubuntu-22.04
    steps:
      - name: Create new branch
        uses: GuillaumeFalourd/create-other-repo-branch-action@v1.5
        with:
          repository_owner: husarion
          repository_name: panther-rpi-os-img
          new_branch_name: ${{ env.RC_BRANCH_NAME }}
          new_branch_ref: ros2-devel
          access_token: ${{ secrets.RAFAL_ACCESS_TOKEN}}

      - name: Build OS image
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: husarion
          repo: panther-rpi-os-img
          github_token: ${{ secrets.RAFAL_ACCESS_TOKEN }}
          workflow_file_name: build_and_deploy_image.yaml
          ref: ${{ env.RC_BRANCH_NAME }}
          client_payload: |
            {
              "dev_image": "true",
              "husarion_ugv_version": "${{ env.RC_BRANCH_NAME }}",
              "image_tag": "${{ github.event.inputs.version }}"
            }

      - name: Build flash OS image
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: husarion
          repo: panther-rpi-os-img
          github_token: ${{ secrets.RAFAL_ACCESS_TOKEN }}
          workflow_file_name: build_and_deploy_flash_os_image.yaml
          ref: ${{ env.RC_BRANCH_NAME }}
          client_payload: |
            {
              "image_tag": "${{ github.event.inputs.version }}"
            }
